services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo:5
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    build: ./user_service
    container_name: user_service
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:secret@postgres_db:5432/user_db

  file_service:
    build: ./file_service
    container_name: file_service
    depends_on:
      - mongo_db
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017
      - MONGODB_DB=files_db

  folder_service:
    build: ./folder_service
    container_name: folder_service
    ports:
      - "8002:8000"

volumes:
  db_data:
  mongo_data:
